version: 2
updates:
  # ğŸ Maintain Python (pip) dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    groups:
      all-pip-dependencies:
        patterns:
          - "*"
